### ISSUE TITLE
Primary banner title is misaligned when title is linked

### ISSUE THREAD

**Issue by chriswales95** [localgovdrupal/localgov_microsites_base#298]
Hi, 

Apologies if this is the wrong issue queue but it does seem to only affect Microsites.

# Issue

We noticed today when we upgraded to V4 of Microsites that there was a styling issue with the primary banner when a link was used (screenshot below). 

![Image](https://github.com/user-attachments/assets/0e42fcce-be1e-4638-8523-1f3c5aeff3e4)

We were able to replicate this on a few client sites and on a fresh Microsite install.

I believe the issue stems from this recent-ish commit in LocalGov Base: https://github.com/localgovdrupal/localgov_base/commit/9bb7f5de853f55aec489e665a01f7bce8d7f27cd

# Replication Steps

1. Install Microsites as per https://github.com/localgovdrupal/localgov_microsites_project/?tab=readme-ov-file#usage
2. Login
3. Create a microsite
4. Edit front page of new microsite
5. Change the secondary banner to a primary banner
6. Ensure a link is present
7. Save and view page

# Proposed solution

The solution we have identified is the deletion of a CSS block in css/components/banner.css in LocalGov Microsites Base.

```css
.banner--primary .banner__link {
  display: block;
  max-width: var(--banner-content-width);
  margin: calc(var(--banner-content-margin) * -1) auto
    var(--banner-content-margin);
}
```

It seems that the margin is the primary issue here but `display: block;` and `max-width: var(--banner-content-width);` also have no effect.

I'll open a PR.
